# Generated by Django 2.2 on 2020-07-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200724_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_comments', to='dashboard.Messages'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster_comments', to='login.User'),
        ),
    ]
